
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

# AppHub Configuration for ABE-CTAS Integration
apphub_project_id = "gen-lang-client-0779767785"
apphub_location = "us-central1"
apphub_application_id = "ctas7-abe-integrated-system"
